name: Deploy with SFTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server: ${{ secrets.HOST }}
          local_path: "./DistSite"
          remote_path: "/home/public"
          sftp_only: true
          delete_remote_files: true
