name: Deploy with SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy with Rsync
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" rsync -e "ssh -o StrictHostKeyChecking=no" --delete-delay -acvz DistSite ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/public
